services:
  - type: pserv
    name: tactic-db
    plan: free
    databaseName: tactic_db
    user: tactic_user

  - type: web
    name: tactic-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tactic-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ENV
        value: production

  - type: web
    name: tactic-frontend
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVarGroups:
      - name: frontend-vars

envVarGroups:
  - name: frontend-vars
    envVars:
      - key: API_URL
        value: https://tactic-5bmd.onrender.com
